Return 401 in all cases of failure
gobuffalo/mw-basicauth pull request #3
Opened 2018-12-05 14:37 UTC by robsliwi

In some cases buffalo would return a 500 instead
of a 401 when the authorization fails.
This commit should fix this behavior, see
discussion in Slack:
https://gophers.slack.com/archives/C3MSAFD40/p1543923920092000

2018-12-05 15:22 UTC, markbates commented
The tests are failing for this, can you please take a look? Thanks.

2018-12-05 15:24 UTC, markbates submitted a review, later dismissed

2018-12-05 15:24 UTC, markbates commented on basicauth.go
> -	// ErrNoCreds is returned when no basic auth credentials are defined
Removing these constitutes a breaking change.

2018-12-05 15:24 UTC, markbates commented on basicauth_test.go
> +	"github.com/robsliwi/mw-basicauth"
Broken import path.

Please read https://github.com/gobuffalo/buffalo/blob/master/.github/CONTRIBUTING.md on how to handle Go PRs.

2019-04-03 15:55 UTC, robsliwi commented
Thanks for the contributing link, should have checked this before making the PR :innocent: 
Updated and rebased it, you can have a second look if you want.

2023-02-09 12:07 UTC, sio4 requested changes
Thank you for your contribution, and sorry for the late review.

Could you please check the comments and fix them? I will proceed with this PR after that.
If you have no interest in this module anymore, not sure since it is already more than four years ago, just ignore this message. I will work on it soon.

2023-02-09 12:07 UTC, sio4 commented on basicauth.go
> +	// ErrUnauthorized is returned in any case the basic authentication fails
extra comment?

2023-02-09 12:07 UTC, sio4 commented on go.mod
> +module github.com/robsliwi/mw-basicauth
it should not be changed.

2023-02-12 19:25 UTC, robsliwi commented
Thanks for picking this up!
Was quite a joy to clone the repo again, set up some Golang-dev-env and get this fixed.

Rebased, pushed, realized two commits, squashed them and all of the requested changes should be included by now :crossed_fingers:

2023-02-13 13:45 UTC, sio4 approved these changes

2023-02-13 13:47 UTC, merged

2023-02-13 13:48 UTC, sio4 commented
Thanks!

2023-02-13 16:16 UTC, sio4 commented
Just for your information, I made some more changes to the topic and filed PR #7. Just in case you are interested.